services:
  - name: example
    target: 'example.service:8000'
    checkers:
      - name: sleeper-put
        success_points: 1
        fail_penalty: 1
        run_options:
          rate:
            times: 1
            per: 10s
          max_goroutines: 0
      - name: sleeper-retrieve
        success_points: 1
        fail_penalty: 1
        run_options:
          rate:
            times: 1
            per: 10s
          max_goroutines: 0
